hello/urls.py
from django.urls import path
from .views import index
from .views import profile
from .views import listbooks
from .views import databooks
from .views import showregistration
from .views import saveregistration
from .views import listsubscribers
# from .views import validation

app_name ='hello'
urlpatterns = [
    path('', index, name='index'),
    path('profile', profile, name='profile'),
    path('listbooks', listbooks, name='listbooks'),
    path('api/books', databooks, name='books'),
    path('registration', showregistration, name='registration'),
    path('saveregistration', saveregistration, name='saveregistration'),
    path('listsubscribers', listsubscribers, name='listsubscribers'),
    # path(r'validation', validation, name='validation')
]

##

ppw_from_Story_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hello.urls'))
]

hello/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	status = models.CharField(max_length=500)
	time = models.DateTimeField(auto_now_add=True)

class Registration(models.Model):
	email = models.EmailField(unique=True)
	name = models.CharField(max_length=100)
	password = models.CharField(max_length=100)

hello/forms.py
from django import forms

class StatusForm(forms.Form):
	attrs = {
		'type': 'text',
		'class': 'form-control'
	}
	status = forms.CharField(label="Status", max_length=300, required=True, widget=forms.TextInput(attrs=attrs))

class RegistForm(forms.Form):
	error_messages={
        'required':'Required Field'
    }
	email_attrs = {
		'type': 'email',
		'class': 'form-control',
		'placeholder' : 'Required'
	}
	name_attrs = {
		'type': 'text',
		'class': 'form-control',
		'placeholder' : 'Required'
	}
	password_attrs = {
		'type': 'password',
		'class': 'form-control',
		'placeholder' : 'Required'
	}
	email = forms.EmailField(label="Email", max_length=25, required=True, widget=forms.EmailInput(attrs=email_attrs))
	name = forms.CharField(label="Name", max_length=100, required=True, widget=forms.TextInput(attrs=name_attrs))
	password = forms.CharField(label="Password", max_length=20, required=True,widget=forms.PasswordInput(attrs=password_attrs))

hello/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db import IntegrityError
from .models import Status
from .models import Registration
from .forms import StatusForm
from .forms import RegistForm
# from django.core.validators import validate_email

import urllib.request, json
import requests

# Create your views here.

def profile(request):
    return render(request, 'profile.html')

def listbooks(request):
	return render(request, 'books.html')

response={}
def index(request):
	response['setstatus'] = StatusForm()
	listStatus = Status.objects.all()
	response['StatusForm'] = listStatus

	form = StatusForm(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		listStatus = Status(status=response['status'])
		listStatus.save()
		return render(request, 'hello.html', response)
	else:
		return render(request, 'hello.html', response)

def databooks(request):
    data_json = requests.get('https://www.googleapis.com/books/v1/volumes?q=architecture').json()
    items = []
    for i in data_json['items']:
        info = {}
        info['title'] = i['volumeInfo']['title']
        info['img'] = i['volumeInfo']['imageLinks']['smallThumbnail'] if 'imageLinks' in i['volumeInfo'].keys() else 'Not Found'
        info['author'] = ", ".join(i['volumeInfo']['authors'])
        info['publishedDate'] = i['volumeInfo']['publishedDate'] if 'publishedDate' in i['volumeInfo'].keys() else 'Not Found'
        items.append(info)
    return JsonResponse({"data" :items})

def showregistration(request):
	form = RegistForm(request.POST)
	html = 'registration.html'
	return render(request,html,{'showform':form})

def saveregistration(request):
	response['showform'] = RegistForm()
	form = RegistForm(request.POST or None)
	if request.method == 'POST' and form.is_valid():
		response['email'] = request.POST['email']
		response['name'] = request.POST['name']
		response['password'] = request.POST['password']
		param = 'True'

		try:
			toStore = Registration(
				email=response['email'],
				name=response['name'],
				password=response['password']
			)
			toStore.save()
			return JsonResponse({'param':param})
		except IntegrityError as e:
			param = 'False'
			return JsonResponse({'param':param})
	elif request.method == 'GET' and form.is_valid():
		data_json = Registration.objects.all()
		items = []
		for i in data_json['items']:
			info={}
			info['email'] = i['email']
			info['name'] = i['name']
			items.append(info)
		return JsonResponse({"data" :items})
	param = 'False'
	return JsonResponse({'param':param})

def listsubscribers(request):
	response['showform'] = RegistForm()
	form = RegistForm(request.GET or None)
	if request.method == 'GET' and form.is_valid:
		data_json = Registration.objects.all()
		for i in data_json['items']:
			info={}
			info['email'] = i['email']
			info['name'] = i['name']
			items.append(info)
	return JsonResponse({"data" :items})

hello/templates/books.html
{% extends "layout/base.html" %}
{% block title %} Books To Read {% endblock %}
{% block content %}

<br><br>

<div class="counter-container">
        <h2>Books I Like</h2>
        <i class ="fa fa-star"></i>: <span class="counters">0</span>
</div>
<br>
<font color="white">
    <table class="table table-hover">
      <thead>
        <th>No</th>
        <th>Title</th>
        <th>Book Cover</th>
        <th>Author(s)</th>
        <th>Published</th>
        <th>Add to Favorite</th>
      </thead>
      <tbody id="bodybooks"></tbody>
</font>

{% endblock %}

hello/templates/hello.html
{% extends "layout/base.html" %}
{% block title %} Hello! {% endblock %}
{% block content %}
        <div class="container">
          <div class="row">
            <div class="col-sm-12" style="padding-top: 25%">
              <h1 align="center">
                  Hello, Apa Kabar?
              </h1>
              <form id="form" method="POST" action="{% url 'hello:index' %}" style="padding-left: 30%; padding-right: 30%;padding-top: 10%;">
                <br>
                {% csrf_token %}
                {% for i in setstatus %}
                  {{i.label_tag}}
                  <br>
                  {{i}}
                {%endfor%}
                <br><br>
                <div align="center">
                  <button type="submit" class="btn btn-success" id="submit-button">Submit</button>
                </div>
              </form>
          </div>
        </div>

        <br><br><br>
            <font color="white">
            <table class="table table-hover">
              <thead>
                <th>Date</th>
                <th>Status</th>
              </thead>
            {% for result in StatusForm %}
              <tbody>
                <td>{{result.time}}</td>
                <td> Status : {{result.status}}</td>
              {% endfor %}
            </tbody>
            </font>

  </div>


{% endblock %}

hello/templates/layout/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <link rel="stylesheet" href="{% static 'mycss.css' %}">
  <!-- Jquery n Bootstrap Script -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="{% static 'myjs.js' %}"></script>
</head>

<body id="myBody">
    <div id="loader"></div>
       <div style="display:none;" id="myDiv" class="animate-bottom">
        <header>
            {% include "partials/header.html" %}
        </header>
        <content>
            <div class="container">
                {% block content %}
                    <!-- content goes here -->
                {% endblock %}
            </div>

        </content>
      </div>
</body>
</html>

hello/templates/partials/header.html
<nav class="navbar navbar-dark fixed-top navbar-expand-md navbar-no-bg" id="navbarsaya">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="listbooks">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link scroll-link" href="registration">Subscribe</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

hello/templates/profile.html
{% extends "layout/base.html" %}
{% block title %} Me {% endblock %}
{% block content %}
    <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
              <font size = "6">
                <br><br>
                <h1 id="profiletitle">Profile</h1>
              </font>
      </div>
    </div>

      <div class="col-sm-12">
          <br><br>
          <img id="sasari" src="https://data.whicdn.com/images/319570132/original.jpg">
      </div>

       <div class="row">
        <div class="col-sm-12" style="text-align: center">
          <font size = "4" color="white">
          <br>
          <p id="name">Name: Dwipuspa Ramadhanti Santoso</p>
          <p id="birthday">Birthday: 22nd December 1999</p>
          <p id="college">Currently Studying At: Faculty of Computer Science, University of Indonesia</p>
        </div>
      </div>

    <br><br>

     <div class="accordion">
      <div class="accordion-header">Current Activities</div>
      <div class="panel">
        <p class="accordion-content">1. Lab PPW<br>2. TP SDA</p>
      </div>

      <div class="accordion-header">Organizations and Committees Record</div>
      <div class="panel">
        <p class="accordion-content">1. Public Relation Staff of The 25th CGT<br>2. HRD of Online Marketing of COMPFEST X<br>3. HRD Staff of DPM Fasilkom UI</p>
      </div>

      <div class="accordion-header">Achievements</div>
      <div class="panel">
        <p class="accordion-content">TBA</p>
      </div>
    </div>

    <br>

    <div align="center">
        <button type="button" class="btn btn-secondary" id="changetheme">Change Theme</button>
    </div>
    <br>
  </div>

{% endblock %}

hello/templates/registration.html
{% extends "layout/base.html" %}
{% block title %} Stay In Touch {% endblock %}
{% block content %}
<div class="container">
          <div class="row">
            <div class="col-sm-12">
            	<br><br><br><br><br><br><br>
            	<h1>Want To Keep In Touch?</h1>
            	
	            	<h3 style="font-style: italic; color: white; text-align: center;">Subscribe Down Below!</h3>
	            	<div id="alert"></div>
	            	<form id="registform" method='POST' action="{% url 'hello:saveregistration' %}" style="padding-left:25%; padding-right: 25%; color:white">
	            	<br><br><br>
	                {% csrf_token %}
	                {% for i in showform %}
	                  {{ i.label_tag }}
	                  {{ i }}
	                {%endfor%}
	                <br><br>
	                <div align="center">
	                	<button type="submit" class="btn btn-success" id="registsubmit">Regist</button>
	              	</div>
	              </form>

	             <font color="white">
				    <table class="table table-hover">
				      <thead>
				        <th>No</th>
				        <th>Name</th>
				        <th>Email</th>
				        <th>Unsubscribe?</th>
				      </thead>
				      <tbody id="bodysubscribers"></tbody>
				</font>

            </div>
        </div>
 </div>
{% endblock %}